name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ZigCI/setup-zig@v1
        with:
          version: 0.14.0
      - run: zig build -Drelease-fast=true
